[phases.setup]
nixPkgs = ["nodejs-20_x", "python3"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npm run build:server"]

[start]
cmd = "NODE_ENV=production node dist-server/index.js"
